### ISSUE TITLE
OS X curl upload issue

### ISSUE THREAD

**Issue by pberry** [ArchiveTeam/fortunecity#2]
I've been having trouble marking uploads as done.  Here is some debug output from curl.

success_str={"downloader":"pberry","item":"es/member/kruzados_norte","bytes":{"member": 16K,"street":0},"version":"20120304.01","id":""}

== Info: About to connect() to focity-2.heroku.com port 80 (#0)
== Info:   Trying 174.129.22.35... == Info: connected
== Info: Connected to focity-2.heroku.com (174.129.22.35) port 80 (#0)
=> Send header, 228 bytes (0xe4)
0000: POST /done HTTP/1.1
0015: User-Agent: curl/7.21.4 (universal-apple-darwin11.0) libcurl/7.2
0055: 1.4 OpenSSL/0.9.8r zlib/1.2.5
0074: Host: focity-2.heroku.com
008f: Accept: _/_
009c: Content-Length: 124
00b1: Content-Type: application/x-www-form-urlencoded
00e2:
=> Send data, 124 bytes (0x7c)
0000: {"downloader":"pberry","item":"es/member/kruzados_norte","bytes"
0040: :{"member": 16K,"street":0},"version":"20120304.01","id":""}
== Info: The requested URL returned error: 500
== Info: Closing connection #0

**Comment by alard** [comment]
Fixed in 30454dadcdb8e844b2bd49bda25e7f4127166e09
